/*
 * To add: create a directory named by user, default site option, specify css
 * (font, colors), write output to a file, error handling, override existing 
 * dir if needed, templates. 
 */
#define _GNU_SOURCE 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#define MAX_LEN 1024

int main() {
	char buffer[MAX_LEN], new_title[MAX_LEN];
	char *title, *c_type, *c_theme, *c_format;
	const char *html_c, *nav_c, *div_c, *padding, *nav_f, *nav_li, *div_f;
	int i = 0, li_tags = 0, type = 0, theme = 0, format = 0;	

	printf("------------------------------------------------------\n");
	printf("Welcome to boil, a command line static site generator!\n");

	printf("Enter a title: ");
	if (fgets(buffer, MAX_LEN, stdin))
  	asprintf(&title, "%s", buffer);

	memset(new_title, 0, MAX_LEN);
	strncpy(new_title, title, strlen(title) - 1);

	while (type != 1 && type != 2 && type != 3) {
		printf("Enter the number of your site type (Blog - 1) (Portfolio - 2) (Course - 3): ");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_type, "%s", buffer);
  	type = atoi(c_type);
	}

	while (theme != 1 && theme != 2 && theme != 3 && theme != 4 && theme != 5) {
		printf("Enter the number of your color theme (Default - 1) (Sky - 2) (Lava - 3) (Pumpkin - 4) (Forest - 5): ");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_theme, "%s", buffer);
  	theme = atoi(c_theme);
	}

	/*
	 * Default has the menu horizontally near the top.
	 * Sidemenu has the menu on the left side. No menu 
	 * has the menu elements distributed on the page, 
	 */
	while (format != 1 && format != 2) {
		printf("Enter the number of your formatting (Default - 1) (Sidemenu - 2)");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_format, "%s", buffer);
  	format = atoi(c_format);
	}

	if (type == 1) {
		li_tags = 2;
	} else if (type == 2) {
		li_tags = 3;
	} else if (type == 3) {
		li_tags = 8;
	}

	if (theme == 1) {
		html_c = "#ffffff";
		nav_c = "#b3b3b3";
		div_c = "#dddddd";
	} else if (theme == 2) {
		html_c = "#99ccff";
		nav_c = "#3b33ff";
		div_c = "#3391ff";
	} else if (theme == 3) {
		html_c = "#f63c3c";
		nav_c = "#ff9900";
		div_c = "#d5d50a";
	} else if (theme == 4) {
		html_c = "#ffc266";
		nav_c = "#afb315";
		div_c = "#60b315";
	} else if (theme == 5) {
		html_c = "#15b32a";
		nav_c = "#006600";
		div_c = "#159eb3";
	} 

	if (format == 1) {
		padding = "5px";
	} else if (format == 2) {
		padding = "25px";
	}

	printf("Your markup:\n<!-- This was generated by boil. -->\n");
	printf("<!DOCTYPE html>\n<head>\n  <title>%s</title>\n</head>\n<body>\n", new_title);

	if (li_tags != 0) {
		printf("  <ul>\n");
		for (i = 0; i < li_tags; i++) 
			printf("   <li></li>\n");
		printf("  </ul>\n");
	}

	printf("  <p></p>\n");

	printf("</body>\n</html>\n");

	system("mkdir site");

	free(title);
	free(c_type);
	free(c_theme);
	free(c_format);

	return 0;
}
