/*
 * To add: create a directory named by user, default site option, specify css
 * (font, colors), write output to a file, error handling, override existing 
 * dir if needed, templates. 
 */
#define _GNU_SOURCE 
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#define MAX_LEN 1024

int main() {
	char buffer[MAX_LEN], new_title[MAX_LEN];
	char *title, *c_type, *c_theme, *c_format;
	const char *html_c, *nav_c, *div_c, *padding, *nav_f, *nav_li, *div_f;
	int type = 0, theme = 0, format = 0;	
	FILE *css;

	printf("------------------------------------------------------\n");
	printf("Welcome to boil, a command line static site generator!\n");

	printf("Enter a title: ");
	if (fgets(buffer, MAX_LEN, stdin))
  	asprintf(&title, "%s", buffer);

	memset(new_title, 0, MAX_LEN);
	strncpy(new_title, title, strlen(title) - 1);

	while (type != 1 && type != 2 && type != 3) {
		printf("Enter the number of your site type (Blog - 1) (Portfolio - 2) (Course - 3): ");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_type, "%s", buffer);
  	type = atoi(c_type);
	}

	while (theme != 1 && theme != 2 && theme != 3 && theme != 4 && theme != 5) {
		printf("Enter the number of your color theme (Default - 1) (Sky - 2) (Lava - 3) (Pumpkin - 4) (Forest - 5): ");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_theme, "%s", buffer);
  	theme = atoi(c_theme);
	}

	/*
	 * Default has the menu horizontally near the top.
	 * Sidemenu has the menu on the left side. No menu 
	 * has the menu elements distributed on the page, 
	 */
	while (format != 1 && format != 2) {
		printf("Enter the number of your formatting (Default - 1) (Sidemenu - 2): ");
		if (fgets(buffer, MAX_LEN, stdin))
  		asprintf(&c_format, "%s", buffer);
  	format = atoi(c_format);
	}

	if (type == 1) {

	} else if (type == 2) {
		
	} else if (type == 3) {
		
	}

	if (theme == 1) {
		html_c = "#ffffff";
		nav_c = "#b3b3b3";
		div_c = "#dddddd";
	} else if (theme == 2) {
		html_c = "#99ccff";
		nav_c = "#3b33ff";
		div_c = "#3391ff";
	} else if (theme == 3) {
		html_c = "#f63c3c";
		nav_c = "#ff9900";
		div_c = "#d5d50a";
	} else if (theme == 4) {
		html_c = "#ffc266";
		nav_c = "#afb315";
		div_c = "#60b315";
	} else if (theme == 5) {
		html_c = "#15b32a";
		nav_c = "#006600";
		div_c = "#159eb3";
	} 

	if (format == 1) {
		padding = "5px";
		nav_f = "display: flex;\n  justify-content: space-around;\n";
		nav_li = "inline-block;\n";
		div_f = "";
	} else if (format == 2) {
		padding = "25px";
		nav_f = "float: left;\n"; 
		nav_li = "block;\n";
		div_f = "\n\tfloat: right;\n  width: 80%;\n";
	}

	printf("Your markup:\n<!-- This was generated by boil. -->\n");
	printf("<!DOCTYPE html>\n<head>\n  <title>%s</title>\n</head>\n<body>\n", new_title);

	printf("  <p></p>\n");

	printf("</body>\n</html>\n");

	system("mkdir site"); 

	css = fopen("theme.css", "w");
	fprintf(css,"/* Default options for color and menu. */\nhtml {\n  font-family: 'Open Sans', sans-serif;\n  margin: 2%%;\n  background-color: %s; \n}\n\nul {\n  list-style-type: none;\n}\n\n#nav { \n  padding: %s; \n  margin: 0;\n  overflow: hidden;\n  background-color: %s; \n  text-align: center;\n  font-size: 18px;\n  %s\n}\n\n#nav-li {\n  display: %s \n}\n\nli a {\n  text-decoration: none;\n  padding: 5px;  \n}\n\n", html_c, padding, nav_c, nav_f, nav_li);
	fprintf(css,"li a:visited {\n  color: black;\n}\n\nli a:hover {\n  color: white;\n}\n\ndiv {\n  background-color: %s;\n  padding-left: 10px;\n  padding-top: 2px;\n  padding-bottom: 2px;\n  font-size: 20px;%s\n}\n\ntable {\n  border-collapse: collapse;\n  width: 90%%;\n  margin-left: auto;\n  margin-right: auto;\n  float: none;\n}\n\nth {\n  background: gray;\n}\n\ntd {\n  background: white;\n}\n\ntd, th {\n  border: 1px solid #000000;\n  text-align: left;\n  padding: 8px;\n}", div_c, div_f); 
	fclose(css);

	system("mv theme.css site");

	free(title);
	free(c_type);
	free(c_theme);
	free(c_format);

	return 0;
}
