/*
 * To add: create a directory named by user, default site option, specify css
 * (font, colors), write output to a file, error handling, override existing 
 * dir if needed, templates. 
 */
#include <stdio.h>
#include <string.h>
#define MAX_LEN 40

int main() {
	char title[MAX_LEN], new_title[MAX_LEN];
	int i, li_tags, type, c_theme, format;

	printf("------------------------------------------------------\n");
	printf("Welcome to boil, a command line static site generator!\n");
	printf("Enter a title (Max length 40): ");
	fgets(title, MAX_LEN, stdin);

	strncpy(new_title, title, strlen(title) - 1); /* Bug? */
	memset(new_title + strlen(title), 0, MAX_LEN - strlen(title));

	while (type != 1 && type != 2 && type != 3) {
		printf("Enter the number of the type of site you want (Blog - 1) (Portfolio - 2) (Course - 3): ");
		scanf("%d", &type);
	}

	/*
	 * Default is black and white. 
	 * Sky is #33F7FF, #3391FF, #3B33FF.
	 * Lava is #D50A0A, #D5700A, #D5D50A.
	 * Pumpkin is #B36815, #AFB315, #60B315.
	 * Forest is #15B32A, #15B379, #159EB3.
	 */
	printf("Enter the number of the color theme you want (Default - 1) (Sky - 2) (Lava - 3) (Pumpkin - 4) (Forest - 5): ");
	scanf("%d", &c_theme);

	/*
	 * Default has the menu horizontally near the top, Antimenu has the menu 
	 * elements distributed on the page, Sidemenu has the menu on the left side.
	 */
	printf("Enter the number of the formatting you want (Default - 1) (No menu - 2) (Sidemenu - 3): ");
	scanf("%d", &format);

	if (c_theme == 1) {

	} else if (c_theme == 2) {

	} else if (c_theme == 3) {

	} else if (c_theme == 4) {

	} else if (c_theme == 5) {

	} 

	if (type == 1) {
		li_tags = 2;
	} else if (type == 2) {
		li_tags = 3;
	} else if (type == 3) {
		li_tags = 8;
	}

	printf("Your markup:\n<!-- This was generated by boil. -->\n");
	printf("body { \n \n \n}\n");
	printf("<!DOCTYPE html>\n<head>\n  <title>%s</title>\n</head>\n<body>\n", new_title);

	if (li_tags != 0) {
		printf("  <ul>\n");
		for (i = 0; i < li_tags; i++) {
			printf("   <li></li>\n");
		}
		printf("  </ul>\n");
	}

	printf("  <p></p>\n");

	printf("</body>\n</html>\n");

	return 0;
}
